{
    'name': 'Multicompany support',
    'version': '1.0',
    'description': 'Multicompany support',
    'summary': 'Multicompany support',
    'author': 'Soy Calidad',
    'website': 'https://www.soycalidad.com',
    'license': 'Other proprietary',
    'category': 'soycalidad',
    'depends': [
        'hola_calidad',
        'mgmtsystem_action',
        'mgmtsystem_audit',
        'mgmtsystem_complaints',
        'mgmtsystem_comunication',
        'mgmtsystem_context',
        'mgmtsystem_employees',
        'mgmtsystem_infrastructure',
        'mgmtsystem_mof',
        'mgmtsystem_legal',
        'mgmtsystem_management_review',
        'mgmtsystem_nonconformity',
        'mgmtsystem_opportunity',
        'mgmtsystem_partner_qualification',
        'mgmtsystem_process',
        'mgmtsystem_process_integration',
        'mgmtsystem_survey',
        'mgmtsystem_target',
        'stock_inspection',
        'dms',
        'soycalidad_improve',
    ],
    'data': [
        'security/multi_company.xml',
        'security/audit_security.xml',
        'security/dms_security.xml',

        'views/action_views.xml',
        'views/audit_views.xml',
        'views/complaint_views.xml',
        'views/comunication_views.xml',
        'views/context_views.xml',
        'views/employee_views.xml',
        'views/hola_calidad_views.xml',
        'views/hr_job_functions_views.xml',
        'views/infrastructure_views.xml',
        'views/legal_views.xml',
        'views/management_review_views.xml',
        'views/mof_views.xml',
        'views/nonconformity_views.xml',
        'views/opportunity_views.xml',
        'views/partner_qualification_views.xml',
        'views/process_integration_views.xml',
        'views/process_views.xml',
        'views/qualitymanual_views.xml',
        'views/survey_views.xml',
        'views/target_views.xml',
        'views/res_partner_views.xml',
        'views/improve_views.xml',
    ],
    'demo': [
    ],
    'auto_install': False,
    'application': False,
}
