{
    'name': 'Multicompany support',
    'version': '1.0',
    'description': 'Multicompany support',
    'summary': 'Multicompany support',
    'author': 'Soy Calidad',
    'website': 'https://www.soycalidad.com',
    'license': 'Other proprietary',
    'category': 'soycalidad',
    'depends': [
        'hola_calidad',
        'mgmtsystem_action',
        'mgmtsystem_audit',
        'mgmtsystem_complaints',
        'mgmtsystem_comunication',
        'mgmtsystem_context',
        'mgmtsystem_employees',
        'mgmtsystem_infrastructure',
        'mgmtsystem_mof',
        'mgmtsystem_legal',
        'mgmtsystem_management_review',
        'mgmtsystem_nonconformity',
        'mgmtsystem_opportunity',
        'mgmtsystem_partner_qualification',
        'mgmtsystem_process',
        'mgmtsystem_process_integration',
        'mgmtsystem_survey',
        'mgmtsystem_target',
        'soycalidad_crm',
        'stock_inspection',
    ],
    'data': [
        'security/multi_company.xml',
        'security/audit_security.xml',

        'views/hola_calidad_views.xml',
        'views/audit_views.xml',
        'views/complaint_views.xml',

    ],
    'demo': [
    ],
    'auto_install': False,
    'application': False,
}
